version: "3.9"
services:
  livestack:
    image: rickbassham/livestack:latest
    build:
      context: .
    volumes:
      - ./data/input:/livestack/input
      - ./data/output:/livestack/output
      - ./data/storage:/livestack/storage
    command: [python, main.py]
    environment:
      - STORAGE_FOLDER=/livestack/storage
      - OUTPUT_FOLDER=/livestack/output
      - INPUT_FOLDER=/livestack/input
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/opt/www/files
    ports:
      - "8080:80"
